### ISSUE TITLE
Can't use height to wrap content?

### ISSUE THREAD

**Issue by yolapop** [MeetMe/Android-HorizontalListView#2]

**Comment by 2020gaurav** [comment]
This issue is still not fixed. We cant give android:layout_height="wrap_content". Please respond....

**Comment by yolapop** [comment]
Apparently this is my mistake for submitting this issue, we all know that Android ListView's width itself cannot be set to `wrap_content`.
Either you set `android:layout_width="match_parent"` or `android:layout_width="somedp"`

**Comment by coolegos** [comment]
But it is not a ListView
