### ISSUE TITLE
 Performance comparison with RecycleView

### ISSUE THREAD

**Issue by LiJianShu0826** [MeetMe/Android-HorizontalListView#35]
hi
Compared with the recycleview provided by Android, who has better performance?
thank you

**Comment by Marchuck** [comment]
> hi
> Compared with the recycleview provided by Android, who has better performance?
> thank you

man, this repository was created 6-7 years ago.
Android evolved by this time, so RecyclerView / ViewPager2 with horizontal orientation is way more reliable
